[package]
name = "controller"
version = "0.1.0"
edition = "2018"
publish = false
license = "Apache-2.0 OR MIT"

[dependencies]
models = { path = "../models", version = "0.1.0" }

futures = "0.3"
# k8s-openapi must match the version required by kube and enable a k8s version feature
k8s-openapi = { version = "0.13.1", default-features = false, features = ["v1_20"] }
kube = { version = "0.63.2", default-features = true, features = [ "derive", "runtime" ] }

snafu = "0.6"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["registry", "env-filter"] }
tracing-bunyan-formatter = "0.3"
opentelemetry = { version = "0.16", features = ["rt-tokio-current-thread"] }
tracing-opentelemetry = "0.16"
